[BUGFIX] Template missing for New->create
Error: Sorry, the requested view was not found. No template was found. View could not be resolved for action "create" in class "In2code\Femanager\Controller\NewController".